### ISSUE TITLE
Feature Request - alarm for a specific time

### ISSUE THREAD

**Issue by snrkl** [vitorgalvao/sandwichtimer#10]
Firstly, thank you for this - it has removed a bunch of crud that was cobbled together and was unreliable.

Feature Request:

Use Case: 
Often, I am managing my time WFH and need to down tools at a particular time for a meeting, or to collect family members etc.

Feature Ask:
A method where a timer for a particular time can be set, so that I don't have to figure out how many minutes away it is.

eg:

alarm @230pm

**Comment by vitorgalvao** [comment]
Thank you for the feature request. I’ve been thinking on this, and ultimately decided not to add it.

macOS Ventura adds the Clock app which has Shortcuts support. Since there’s a `shortcuts` command-line tool, it’s now possible to replicate the timer functionality *plus* add alarms! A few things are lost, like pomodoros or only showing minutes, but I can live with the tradeoff.

This app exists mostly so I can interface with it via [Alfred](https://www.alfredapp.com), so when I update [the workflow](https://github.com/vitorgalvao/alfred-workflows/tree/master/SandwichTimer) I’ll deprecate this.
