### ISSUE TITLE
SandwichTimer no longer plays audio when timer completes

### ISSUE THREAD

**Issue by scotthmurray** [vitorgalvao/sandwichtimer#9]
Hi! I love SandwichTimer and use it with your Alfred workflow. Thank you for all of your work creating it.

I recently updated to MacOS 12.3.1 (Monterey) and have noticed that the SandwichTimer no longer plays audio (the "beep" or trill sound) when a timer completes.  The menubar item updates to show "x min timer over" but there's no audio.

I didn't notice exactly when the audio stopped working — whether that was after updating to Monterey, or independent of that.

What troubleshooting steps would you recommend? Uninstall, reboot, and reinstall fresh?

Any ideas appreciated!

**Comment by vitorgalvao** [comment]
Hello, and thank you for the kind words.

Can’t reproduce, it still plays the audio here. The sound is part of the notification, so first make sure you don’t have Do Not Disturb on, then check if notifications are enabled (System Preferences → Notificaitons & Focus).

**Comment by scotthmurray** [comment]
Vítor, wow, you are so kind to reply!

Thank you for the tip. I got it working again. I:

- deleted the app and Alfred workflow
- restarted
- reinstalled fresh
- ran the timer
- when the first timer completed, then Notifications Center prompted for permissions to give me notifications
- then I tweaked some settings in Preferences

Now the audio is back, though the notifications are repeated "beep" sounds.  Didn't the timer used to play a "trill"-like sound, that was specific to SandwichTimer?  My Mac is now using the default "notification" sound, and the notification appears over and over and over (beep! beep! beep!) with a new banner each time (accumulating!) until I quit the timer app.

So this works for me; I just wonder if that's how it's *supposed* to work!

**Comment by vitorgalvao** [comment]
> then Notifications Center prompted for permissions to give me notifications

macOS’ permissions are known to get wonky some times, so that makes sense.

> Didn't the timer used to play a "trill"-like sound, that was specific to SandwichTimer?

Nope, it was always a standard sound, though [it’s different pre and post Big Sur](https://github.com/vitorgalvao/sandwichtimer/blob/b097ca423c0ab6dc8304724329788685755f6853/app/main.js#L51).

> and the notification appears over and over and over (beep! beep! beep!) with a new banner each time (accumulating!) until I quit the timer app.

[For timers, that’s intended behaviour](https://github.com/vitorgalvao/sandwichtimer/blob/b097ca423c0ab6dc8304724329788685755f6853/app/main.js#L198). It’s so you don’t miss it if you were away from the keyboard at the time.

Do note that once Ventura is out, I plan on revising it and probably changing it to use the new Clock app instead of the bespoke one. We’ll see how it works in practice.

> wow, you are so kind to reply!

I try to always do so and get some kind of resolution or closure. That’s why the repos I manage tend to have zero or very few open issues, I like to keep them tidy!

Glad it’s now working for you. Have a nice week.

**Comment by scotthmurray** [comment]
Wonderful, I appreciate you taking the time to share this.

(And I happened to notice that your repos are suuuuuuper clean!) 😁
